require 'bundler'
require "rubygems/package"

RIPPLE_CLI_FOLDER = File.dirname(__FILE__)

module Bundler
  class GemHelper
    class << self
      def install_tasks(opts = {})
        opts[:name] = 'ripple-cli'
        opts[:dir] = File.dirname(__FILE__)
        new(opts[:dir], opts[:name]).install
      end
    end

    def build_gem
      @gemspec = Bundler.load_gemspec(@spec_path)

      puts @gemspec.files

      Dir.chdir(RIPPLE_CLI_FOLDER) do
        Gem::Package::build @gemspec, true
      end
    end
  end
end

namespace :gem do
  require "bundler/gem_tasks"

  task :archive => %w{compile prepare_bin build} do
    Dir.chdir(RIPPLE_CLI_FOLDER) do
      copyOutputFiles '.', '*.gem', ARTIFACTS
    end
  end

  desc "publishes an official release of the build artifacts"
  task :publish do
    gem_file = Dir.glob("artifacts/*.gem").sort.last
    sh("gem push #{gem_file}")

  end

  task :prepare_bin => :clean do
    dir = "src/ripple/bin/#{COMPILE_TARGET}/"

    FileUtils.cp_r "#{dir}/.", File.expand_path('bin/ripple_exe/.', RIPPLE_CLI_FOLDER)
  end

  task :clean do
    Dir.chdir(RIPPLE_CLI_FOLDER) do
      ['bin/ripple_exe'].each do |d|
        FileUtils.rm_rf d
        FileUtils.mkdir_p d
      end

      Dir.glob("*.gem").each  do |f|
        FileUtils.rm f
      end

    end
  end
end
